// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestEaseClientGenerator.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "7c7becf7-5f28-4b91-bc4c-6491845c6fe3";
        public const string Name = "RestEase Client Code Generator";
        public const string Description = @"Generate a RestEase compatible client based on a Swagger / OpenAPI or RAML specification.";
        public const string Language = "en-US";
        public const string Version = "1.0.10";
        public const string Author = "Stef Heyenrath";
        public const string Tags = "OpenAPI; Swagger; RestEase; REST API; Code Generator; REST Client; RAML";
    }
}
