// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestEaseClientGenerator.VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "47afe4e1-0000-4fe1-8ca7-edb8310bda4a";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidUIContextString = "a3381e62-0000-436f-824e-5f0097387c11";
        public static Guid guidUIContext = new Guid(guidUIContextString);

        public const string guidPackageCmdSetString = "c292653b-0000-4b8c-b672-3375d8561881";
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);

        public const string guidNewRestApiClientContextString = "7cec8679-c1b8-48bf-9fa4-5faa38cbe0fa";
        public static Guid guidNewRestApiClientContext = new Guid(guidNewRestApiClientContextString);

        public const string guidNewRestApiClientCmdSetString = "e4b99f94-0000-4caa-adcd-24302c232938";
        public static Guid guidNewRestApiClientCmdSet = new Guid(guidNewRestApiClientCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SubmenuGroup = 0x1020;
        public const int CommandsGroup = 0x1021;
        public const int Submenu = 0x0100;
        public const int RestEaseCodeGeneratorCustomToolSetter = 0x0200;
        public const int NewSubmenuGroup = 0x1020;
        public const int NewCommandsGroup = 0x1021;
        public const int NewSubmenu = 0x0100;
        public const int GenerateWithRestEase = 0x0200;
    }
}