namespace MicrosoftExampleConsoleApp.MicrosoftWebAppServicePlans.Models
{
    /// <summary>
    /// Level of the most severe insight generated by the detector.
    /// </summary>
    public static class StatusStatusIdConstants
    {
        public const string Critical = "Critical";

        public const string Warning = "Warning";

        public const string Info = "Info";

        public const string Success = "Success";

        public const string None = "None";
    }
}
