using System;
using System.Collections.Generic;

namespace MicrosoftExampleConsoleApp.MicrosoftWebAppServicePlans.Models
{
    /// <summary>
    /// Identify the status of the most severe insight generated by the detector.
    /// </summary>
    public class Status
    {
        /// <summary>
        /// Descriptive message.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Level of the most severe insight generated by the detector.
        /// </summary>
        public string StatusId { get; set; }
    }
}