#%RAML 1.0
title: MediaWiki
version: v1
baseUri: https://en.wikipedia.org/w/api.php
description: The MediaWiki action API is a web service that provides convenient access to wiki features, data, and meta-data over HTTP, via a URL usually at api.php
mediaType: application/json
types:
  NormalizedItem:
    type: object
    properties:
      from: string
      to: string
  Pages:
    type: object
    properties:
      [\d]:
        type: object
        properties:
          ns?: number
          title?: string
          missing?: string
  Normalization:
    type: object
    properties:
      query:
        type: object
        properties:
          normalized: NormalizedItem[]
          pages: Pages
    example:
      query:
        normalized:
          - from: "Project:articleA"
            to: "Wikipedia:ArticleA"
        pages:
          1:
            ns: 4
            title: "Wikipedia:ArticleA"
            missing: ""
  QueryResult:
    type: object
    properties:
      query:
        type: object
        properties:
          pages: Pages
    example:
      query:
        pages:
          1:
            ns: 4
            title: "Wikipedia:ArticleA"
            missing: ""
  Destination:
    type: object
    properties:
      from: string
      to: string
  RedirectsQuery:
    type: object
    properties:
      query:
        type: object
        properties:
          redirects: Destination
          pages: Pages
    example:
      query:
        redirects:
          from: "Main page"
          to: "Main Page"
        pages:
          1:
            ns: 4
            title: "Wikipedia:ArticleA"
            missing: ""
  Page:
    type: object
    properties:
      ns?: number
      title?: string
      pageid?: string
    example:
      ns: "10"
      title: "Template:API Intro"
      pageid: "16385"
  ExportQuery:
    type: object
    properties:
      query:
        type: object
        properties:
          pages: Page[]
          export: object
    example:
      query:
        pages:
          ns: "10"
          title: "Template:API Intro"
          pageid: "16385"
        export: null
  PagesLists:
    type: object
    properties:
      query:
        type: object
        properties:
          pageids: string[]
          pages:
            type: object
            properties:
              [\w]:
                type: object
                properties:
                  pageid: number
                  ns: number
                  title: string
/:
  put: 
    is: [ hasWorkflowName ]
    description: Update the scheme to include the passed mapping. The body is a representation of the workflow mapping. Values not passed are assumed to indicate no change for that field. The passed representation can have its updateDraftIfNeeded flag set to true to indicate that the draft should be created/updated when the actual scheme cannot be edited.
    body: 
        application/json: 
        schema: workflowMappingsReq
        example: !include examples/workflowMappingsReq-example.json
    responses: 
        401: 
        description: Returned if there is no user or if the user has not entered a websudo session.
  get:
    description: Title normalization | Missing and invalid titles | Resolving redirects | Exporting pages | Getting a list of page IDs
    queryParameters:
      action:
        required: true
        enum: [ query ]
      titles:
        required: true
        enum: [A|B|C]
      format:
        enum: [jsonfm]
      redirects:
      generator:
        enum: [templates]
      export:
      indexpageids:
    responses:
      200:
        body:
          application/json:
            type: Normalization | QueryResult | RedirectsQuery | ExportQuery | PagesLists
