using System;
using System.Collections.Generic;

namespace MicrosoftExampleConsoleApp.MicrosoftWebApps.Models
{
    /// <summary>
    /// DetectorResponse resource specific properties
    /// </summary>
    public class DetectorResponseProperties
    {
        /// <summary>
        /// Definition of Detector
        /// </summary>
        public DetectorInfo Metadata { get; set; }

        /// <summary>
        /// Data Set
        /// </summary>
        public DiagnosticData[] Dataset { get; set; }

        /// <summary>
        /// Identify the status of the most severe insight generated by the detector.
        /// </summary>
        public Status Status { get; set; }

        /// <summary>
        /// Additional configuration for different data providers to be used by the UI
        /// </summary>
        public DataProviderMetadata[] DataProvidersMetadata { get; set; }

        /// <summary>
        /// Suggested utterances where the detector can be applicable
        /// </summary>
        public QueryUtterancesResults SuggestedUtterances { get; set; }
    }
}