using System;
using System.Collections.Generic;

namespace RestEaseClientGeneratorConsoleApp.Examples.MicrosoftStorage.Models
{
    /// <summary>
    /// The Storage Account Local User properties.
    /// </summary>
    public class LocalUserProperties
    {
        /// <summary>
        /// The permission scopes of the local user.
        /// </summary>
        public PermissionScope[] PermissionScopes { get; set; }

        /// <summary>
        /// Optional, local user home directory.
        /// </summary>
        public string HomeDirectory { get; set; }

        /// <summary>
        /// Optional, local user ssh authorized keys for SFTP.
        /// </summary>
        public SshPublicKey[] SshAuthorizedKeys { get; set; }

        /// <summary>
        /// A unique Security Identifier that is generated by the server.
        /// </summary>
        public string Sid { get; set; }

        /// <summary>
        /// Indicates whether shared key exists. Set it to false to remove existing shared key.
        /// </summary>
        public bool HasSharedKey { get; set; }

        /// <summary>
        /// Indicates whether ssh key exists. Set it to false to remove existing SSH key.
        /// </summary>
        public bool HasSshKey { get; set; }

        /// <summary>
        /// Indicates whether ssh password exists. Set it to false to remove existing SSH password.
        /// </summary>
        public bool HasSshPassword { get; set; }
    }
}