using System;
using System.Collections.Generic;

namespace RestEaseClientGeneratorConsoleApp.Examples.MicrosoftStorage.Models
{
    /// <summary>
    /// The Storage Account Local User keys.
    /// </summary>
    public class LocalUserKeys
    {
        /// <summary>
        /// Optional, local user ssh authorized keys for SFTP.
        /// </summary>
        public SshPublicKey[] SshAuthorizedKeys { get; set; }

        /// <summary>
        /// Auto generated by the server for SMB authentication.
        /// </summary>
        public string SharedKey { get; set; }
    }
}